version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  build:
    commands:
      - npm prisma generate
      - npm build
artifacts:
  files:
    - '**/*'
